/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface CvHeaderLink {
      'alt': string;
      'href': string;
      'image': string;
    }
  }

  interface HTMLCvHeaderLinkElement extends StencilComponents.CvHeaderLink, HTMLStencilElement {}

  var HTMLCvHeaderLinkElement: {
    prototype: HTMLCvHeaderLinkElement;
    new (): HTMLCvHeaderLinkElement;
  };
  interface HTMLElementTagNameMap {
    'cv-header-link': HTMLCvHeaderLinkElement;
  }
  interface ElementTagNameMap {
    'cv-header-link': HTMLCvHeaderLinkElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-header-link': JSXElements.CvHeaderLinkAttributes;
    }
  }
  namespace JSXElements {
    export interface CvHeaderLinkAttributes extends HTMLAttributes {
      'alt'?: string;
      'href'?: string;
      'image'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvHeaderMeta {

    }
  }

  interface HTMLCvHeaderMetaElement extends StencilComponents.CvHeaderMeta, HTMLStencilElement {}

  var HTMLCvHeaderMetaElement: {
    prototype: HTMLCvHeaderMetaElement;
    new (): HTMLCvHeaderMetaElement;
  };
  interface HTMLElementTagNameMap {
    'cv-header-meta': HTMLCvHeaderMetaElement;
  }
  interface ElementTagNameMap {
    'cv-header-meta': HTMLCvHeaderMetaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-header-meta': JSXElements.CvHeaderMetaAttributes;
    }
  }
  namespace JSXElements {
    export interface CvHeaderMetaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvHeader {

    }
  }

  interface HTMLCvHeaderElement extends StencilComponents.CvHeader, HTMLStencilElement {}

  var HTMLCvHeaderElement: {
    prototype: HTMLCvHeaderElement;
    new (): HTMLCvHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'cv-header': HTMLCvHeaderElement;
  }
  interface ElementTagNameMap {
    'cv-header': HTMLCvHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-header': JSXElements.CvHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface CvHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvPage {

    }
  }

  interface HTMLCvPageElement extends StencilComponents.CvPage, HTMLStencilElement {}

  var HTMLCvPageElement: {
    prototype: HTMLCvPageElement;
    new (): HTMLCvPageElement;
  };
  interface HTMLElementTagNameMap {
    'cv-page': HTMLCvPageElement;
  }
  interface ElementTagNameMap {
    'cv-page': HTMLCvPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-page': JSXElements.CvPageAttributes;
    }
  }
  namespace JSXElements {
    export interface CvPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvPortfolioCard {
      'img': string;
    }
  }

  interface HTMLCvPortfolioCardElement extends StencilComponents.CvPortfolioCard, HTMLStencilElement {}

  var HTMLCvPortfolioCardElement: {
    prototype: HTMLCvPortfolioCardElement;
    new (): HTMLCvPortfolioCardElement;
  };
  interface HTMLElementTagNameMap {
    'cv-portfolio-card': HTMLCvPortfolioCardElement;
  }
  interface ElementTagNameMap {
    'cv-portfolio-card': HTMLCvPortfolioCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-portfolio-card': JSXElements.CvPortfolioCardAttributes;
    }
  }
  namespace JSXElements {
    export interface CvPortfolioCardAttributes extends HTMLAttributes {
      'img'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvSection {
      'img': string;
    }
  }

  interface HTMLCvSectionElement extends StencilComponents.CvSection, HTMLStencilElement {}

  var HTMLCvSectionElement: {
    prototype: HTMLCvSectionElement;
    new (): HTMLCvSectionElement;
  };
  interface HTMLElementTagNameMap {
    'cv-section': HTMLCvSectionElement;
  }
  interface ElementTagNameMap {
    'cv-section': HTMLCvSectionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-section': JSXElements.CvSectionAttributes;
    }
  }
  namespace JSXElements {
    export interface CvSectionAttributes extends HTMLAttributes {
      'img'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvTagCloudHeader {

    }
  }

  interface HTMLCvTagCloudHeaderElement extends StencilComponents.CvTagCloudHeader, HTMLStencilElement {}

  var HTMLCvTagCloudHeaderElement: {
    prototype: HTMLCvTagCloudHeaderElement;
    new (): HTMLCvTagCloudHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'cv-tag-cloud-header': HTMLCvTagCloudHeaderElement;
  }
  interface ElementTagNameMap {
    'cv-tag-cloud-header': HTMLCvTagCloudHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-tag-cloud-header': JSXElements.CvTagCloudHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface CvTagCloudHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface CvTagCloud {

    }
  }

  interface HTMLCvTagCloudElement extends StencilComponents.CvTagCloud, HTMLStencilElement {}

  var HTMLCvTagCloudElement: {
    prototype: HTMLCvTagCloudElement;
    new (): HTMLCvTagCloudElement;
  };
  interface HTMLElementTagNameMap {
    'cv-tag-cloud': HTMLCvTagCloudElement;
  }
  interface ElementTagNameMap {
    'cv-tag-cloud': HTMLCvTagCloudElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'cv-tag-cloud': JSXElements.CvTagCloudAttributes;
    }
  }
  namespace JSXElements {
    export interface CvTagCloudAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
